# Workflow name
name: Build image to development

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - 'README.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - 'README.md'

# Just one job at this time
jobs:

  # Job name
  Job-Docker-Build-Dev:

    # Github Action runner
    runs-on: ubuntu-latest

    # Job condition to run
    if: startsWith(github.event.repository.name, 'repo-name1') || startsWith(github.event.repository.name, 'repo-name2')

    # Tasks
    steps:

      - name: Checkout repository as working directory
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true

      - name: Set TAG
        id: GET_TAG
        run: |
          # Get TAG on format expected by Flux for get latest from correct sorting
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          echo ::set-output name=TAG::$(date -u +${SHORT_SHA}-%Y%m%dT%H%M)

      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}

      - name: Docker Build and Push
        id: build
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: APP_ENV=development
          push: ${{ github.event_name != 'pull_request' }}
          tags: account/${{ github.event.repository.name }}:${{ steps.GET_TAG.outputs.TAG }}
